### ISSUE TITLE
Vagrant up runs in error

### ISSUE THREAD

**Issue by de-wiring** [socketplane/socketplane#103]
Vagrantfile uses socketplane-specific box url on S3. Please switch to native ubuntu or make box url configurable, i.e. by ENV variables.

**Comment by dave-tucker** [comment]
@de-wiring it's because we include all of our dependencies to minimize build time and bandwidth usage.
Without the socketplane/ubuntu-14.10 image (which is a single 700MB download), each host needs to fetch hundreds of MB of packages and docker images, so the spin up time of 3 VMs gets insane depending on your bandwitdh. I've raised a PR as we've moved this box to be hosted on Atlas (formerly Vagrant Cloud).

**Comment by de-wiring** [comment]
thx!
