### ISSUE TITLE
Downloading socketplane to windows thru git causes "^M" issue

### ISSUE THREAD

**Issue by smakam** [socketplane/socketplane#104]
When we do "vagrant up" in windows, get the following error:
==> socketplane-2: /tmp/vagrant-shell: /usr/bin/socketplane: /bin/sh^M: bad interpreter: No such file or directory

Workaround:
Run "dos2unix" on the scripts directory to remove "^M" 

1 way to fix this would be by adding .gitattributes like this:
*        text eol=lf
*.sh     text eol=lf
*.rb     text eol=lf
bin\*    text eol=lf

**Comment by dave-tucker** [comment]
The `.gitattributes` would work, but our line-ending are already in Unix format :)
I wonder if the best fix for windows users is to update their global `.gitconfig` as explained [here](https://help.github.com/articles/dealing-with-line-endings/#global-settings-for-line-endings). This would fix the issue for all repositories rather than just ours.

**Comment by smakam** [comment]
Hi Dave
I agree with you that updating global .gitconfig for windows is a better approach. I will close the issue in that case.

Thanks
Sreenivas
